apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-allowed-empty-dir-violation
spec:
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - name: container2
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    volumeMounts:
    - mountPath: /cache2
      name: demo-vol
  volumes:
  - name: cache-volume
    hostPath:
      path: /tmp
  - name: demo-vol
    emptyDir: {}