apiVersion: v1
kind: Node
metadata:
  name: kind-control-plane # existed node
  labels:
    key1: val2  
spec:
  unschedulable: false

---

apiVersion: v1
kind: Node
metadata:
  name: kind-control-plane # existed node
  labels:
    key1: val1
spec:
  unschedulable: false
