apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
  labels:
    app: scenario-pass-exclusion
spec:
  hostNetwork: true
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: image-exception
    image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
