apiVersion: v1
appVersion: 1.0
description: Helm chart for deploying Azure Policy Add-on on Azure Arc enabled Kubernetes clusters.
name: azure-policy-addon-arc-clusters
version: 1.0.0
keywords:
  - azure
  - azure policy
  - azure-policy
  - governance
  - compliance
  - gatekeeper
  - opa
  - kubernetes policy
  - kubernetes-policy
  - arc connected clusters
  - arc-connected-clusters
  - arc clusters
  - arc-clusters
  - azure arc enabled kubernetes clusters
  - azure-arc-enabled-kubernetes-clusters
  - kubernetes
home: https://aka.ms/kubepolicydoc
maintainers:
  - name: azuredg
    email: azuredg@microsoft.com
