apiVersion: v1
kind: Pod
metadata:
  name: pass-empty
spec:
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/nanoserver:1809
    command:
      - "ping"
      - "-t"
      - "127.0.0.1"
  nodeSelector:
    "kubernetes.io/os": windows
# Nano Server based images run as ContainerUser by default