apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
spec:
  securityContext:
    windowsOptions:
      runAsUserName: "ContainerAdmin"
  containers:
  - name: image-exclude
    image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
    command:
      - "ping"
      - "-t"
      - "127.0.0.1"
  nodeSelector:
    "kubernetes.io/os": windows