apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
  labels:
    app: scenario-read-only-root-filesystem
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude # bypassed by the container exclusion parameter
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    securityContext:
      readOnlyRootFilesystem: false
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  - name: image-exclude
    image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
    securityContext:
      readOnlyRootFilesystem: false
