apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude # bypassed by the container exclusion parameter
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: 5
        memory: 100M 
  - name: image-exclude
    image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
    resources:
      limits:
        cpu: 5
        memory: 100M 