apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
  labels:
    app: scenario-container-allowed-ports
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude # bypassed by the container exclusion parameter
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    ports:
    - containerPort: 80