apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-allowed-host-path-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
      readOnly: true
  volumes:
  - name: cache-volume
    hostPath:
      path: /tmp # /tmp is not in allowedHostPath and it is mounted
