kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: violation-example
provisioner: kubernetes.io/azure-disk # detects this field
reclaimPolicy: Delete
parameters:
  storageAccountType: Premium_LRS
