apiVersion: v1
kind: Pod
metadata:
  name: violation-undefined
  labels:
    app: scenario-block-default-namespace-violation
spec:
  containers:
    - name: container1
      image: mcr.microsoft.com/aks/policy/example:v1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: violation-undefined-service
spec:
  ports:
  - port: 8080
