apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
  labels:
    app: scenario-container-allowed-images
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude 
    image: excluded-image # bypassed by the container exclusion parameter
    ports:
    - containerPort: 8080