apiVersion: v1
kind: Pod
metadata:
  name: violation-no-tag
  labels:
    app: scenario-container-allowed-pull-policy-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example # pullPolicy will be set Always, referring to https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting