apiVersion: v1
kind: Node
metadata:
  name: kind-control-plane # system node
  labels:
    kubernetes.azure.com/mode: System
spec:
  unschedulable: false
  taints:
    - key: NonCriticalAddonsOnly
      value: val1
      effect: NoSchedule