apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: unconfined
    container.seccomp.security.alpha.kubernetes.io/nginx: unconfined # not in "allowedProfiles"
  labels:
    app: scenario-allowed-seccomp-profiles-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
