apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-disallowed-host-paths
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  volumes:
  - name: cache-volume
    hostPath:
      path: /tmp # directory location on host
