apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-container-allowed-ports-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    ports:
    - containerPort: 80 # detects this field