apiVersion: v1
kind: Pod
metadata:
    name: violation-example
    labels:
        app: scenario-selinux-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    securityContext:
      seLinuxOptions:
        level: s1:c234,c567
        user: sysadm_u
        role: sysadm_r
        type: svirt_lxc_net_t
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
