apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-block-host-namespace-violation
spec:
  hostPID: true # detects this field
  hostIPC: true # detects this field
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
