apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-allow-host-network-port-violation
spec:
  hostNetwork: true
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    ports:
    - containerPort: 9001
      hostPort: 9001 # detects this field
