apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-full-property-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    supplementalGroups:
      - 250
    fsGroup: 250
  containers:
    - name: container1
      image: mcr.microsoft.com/aks/policy/example:v1.0.0
      securityContext:
        runAsUser: 250
        runAsGroup: 250
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
