apiVersion: v1
kind: Pod
metadata:
  name: pass-local-host-profile
  labels:
    app: scenario-allowed-seccomp-profiles
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/allow.json # matches "localhost/profiles/allow.json"
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
