apiVersion: v1
kind: Pod
metadata:
  name: pass-runtime-default-security-context
  labels:
    app: scenario-allowed-seccomp-profiles
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    seccompProfile:
      type: RuntimeDefault # matches "runtime/default", "docker/default"
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
