apiVersion: v1
kind: Pod
metadata:
  name: pass-runtime-default-annotation
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    container.seccomp.security.alpha.kubernetes.io/container1: runtime/default # matches "runtime/default"
  labels:
    app: scenario-allowed-seccomp-profiles
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
