apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: unconfined
    container.seccomp.security.alpha.kubernetes.io/nginx: unconfined
  labels:
    app: scenario-allowed-seccomp-profiles
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude # bypassed by the container exclusion parameter
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  - name: image-exclude
    image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
