apiVersion: v1
kind: Pod
metadata:
  name: pass-windows
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: unconfined
    container.seccomp.security.alpha.kubernetes.io/nginx: unconfined
  labels:
    app: scenario-allowed-seccomp-profiles
spec:
  nodeSelector:
    kubernetes.io/os: windows # will bypass windows containers
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
