apiVersion: v1
kind: Pod
metadata:
  name: pass-windows
  labels:
    app: scenario-range-without-max
spec:
  nodeSelector:
    kubernetes.io/os: windows # will bypass windows containers
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
    securityContext:
        runAsUser: 50
        runAsGroup: 50
  securityContext:
    supplementalGroups:
      - 50
    fsGroup: 50
