apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
  labels:
    app: scenario-range-without-max
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    supplementalGroups:
      - 50
    fsGroup: 50
  containers:
    - name: container-exclude # bypassed by the container exclusion parameter
      image: mcr.microsoft.com/aks/policy/example:v1.0.0
      securityContext:
        runAsUser: 50
        runAsGroup: 50
    - name: image-exclude
      image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
      securityContext:
        runAsUser: 50
        runAsGroup: 50
