apiVersion: v1
kind: Service
metadata:
  name: pass-allowed-port-range
spec:
  selector:
    app: MyApp
  ports:
    - port: 4333 # matches "4000-5000"
      targetPort: 80
      nodePort: 30008
  type: NodePort
