apiVersion: v1
kind: Service
metadata:
  name: pass-allowed-port
spec:
  selector:
    app: MyApp
  ports:
    - port: 9999 # matches "9999"
      targetPort: 80
      nodePort: 30007
  type: NodePort