apiVersion: v1
kind: Pod
metadata:
  name: pass-windows
  labels:
    app: scenario-allow-host-network-port
spec:
  hostNetwork: true
  nodeSelector:
    kubernetes.io/os: windows # will bypass windows containers
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
    ports:
    - containerPort: 10000
      hostPort: 10000
