apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-allow-host-network-port
spec:
  hostNetwork: false
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    ports:
    - containerPort: 8000
      hostPort: 8000 # detects this field
