apiVersion: v1
kind: Pod
metadata:
  name: violation-non-root-false
  labels:
    app: scenario-run-as-non-root-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
      runAsNonRoot: true
  containers:
    - name: container1
      image: mcr.microsoft.com/aks/policy/example:v1.0.0
      securityContext:
        runAsNonRoot: false
