apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-range-without-max-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    supplementalGroups:
      - 50
    fsGroup: 50
  containers:
    - name: container1
      image: mcr.microsoft.com/aks/policy/example:v1.0.0
      securityContext:
        runAsUser: 50
        runAsGroup: 50
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
