apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
  labels:
    app: scenario-allowed-empty-dir
spec:
  automountServiceAccountToken: false
  containers:
  - name: image-exclude
    image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    hostPath:
      path: /tmp
