apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-allowed-empty-dir
spec:
  automountServiceAccountToken: false
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    volumeMounts:
    - mountPath: /cache2
      name: demo-vol
  volumes:
  - name: demo-vol
    emptyDir: {} # detects this field
