apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-account
---
apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-block-automount-token
spec:
  serviceAccountName: test-account
  automountServiceAccountToken: false # detects this field
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"