apiVersion: v1
kind: Service
metadata:
  name: pass-example
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs: # detects this field
    - 203.0.113.0
