apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-account-bad-2

---
apiVersion: v1
kind: Pod
metadata:
  name: violation-automount
  labels:
    app: scenario-block-automount-token-violation
spec:
  serviceAccountName: test-account-bad-2
  automountServiceAccountToken: true # detects this field
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
