apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-account-bad
---
apiVersion: v1
kind: Pod
metadata:
  name: violation-mount
  labels:
    app: scenario-block-automount-token-violation
spec:
  serviceAccountName: test-account-bad
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount # detects this field
      name: default-token-l9xgc
      readOnly: true
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  volumes:
  - name: default-token-l9xgc
    secret:
      defaultMode: 420
      secretName: default-token-l9xgc
