apiVersion: v1
kind: Pod
metadata:
  name: violation-automount-undefined
  labels:
    app: scenario-block-automount-token-violation
spec:
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
