apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    kubernetes.azure.com: violation
    env: dev
spec:
  containers:
  - name: my-container
    image: busybox
    resources:
      limits:
        cpu: 100m
        memory: 100M    
    imagePullPolicy: IfNotPresent