apiVersion: v1
kind: Pod
metadata:
  name: violation-pod-uid
  labels:
    app: scenario-container-no-privilege-escalation-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    runAsUser: 200 # runAsUser != 0 && allowPrivilegeEscalation==false is also considered violation
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
