apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-container-no-privilege-escalation-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    securityContext:
      allowPrivilegeEscalation: true # detects this field