apiVersion: v1
kind: Pod
metadata:
  name: violation-miss-limit
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0