apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-block-naked-pods-violation
spec:
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
