apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
  labels:
    app: scenario-full-property
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    supplementalGroups:
      - 250
    fsGroup: 250
  containers:
    - name: container-exclude # bypassed by the container exclusion parameter
      image: mcr.microsoft.com/aks/policy/example:v1.0.0
      securityContext:
        runAsUser: 250
        runAsGroup: 250
    - name: image-exclude
      image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
      securityContext:
        runAsUser: 250
        runAsGroup: 250
