apiVersion: v1
kind: Pod
metadata:
  name: violation
  labels:
    app: scenario-inline-cert
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: image-unsinged
    image: ghcr.io/deislabs/ratify/notary-image:unsigned