apiVersion: v1
kind: Pod
metadata:
  name: pass-exclusion
  annotations:
    apparmor.security.beta.kubernetes.io/pod: unconfined
    container.apparmor.security.beta.kubernetes.io/container-exclude: unconfined
  labels:
    app: scenario-runtime-default
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude # bypassed by the container exclusion parameter
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
  - name: image-exclude
    image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
