apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  annotations:
    # Assuming policy applied with allowedProfiles including 'runtime/default'
    apparmor.security.beta.kubernetes.io/pod: runtime/default
    container.apparmor.security.beta.kubernetes.io/container1: runtime/default
  labels:
    app: scenario-runtime-default
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
  - name: container2
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
