apiVersion: v1
kind: Pod
metadata:
  name: pass-windows
  annotations:
    apparmor.security.beta.kubernetes.io/pod: unconfined
    container.apparmor.security.beta.kubernetes.io/windows-server: unconfined
  labels:
    app: scenario-runtime-default
spec:
  nodeSelector:
    kubernetes.io/os: windows # will bypass windows containers
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
