apiVersion: v1
kind: Pod
metadata:
  name: pass-uid
  labels:
    app: scenario-container-no-privilege-escalation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    runAsUser: 200
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    securityContext:
      runAsUser: 0 # detects this field
