apiVersion: v1
kind: Pod
metadata:
  name: violation-miss-liveness-probe
  labels:
    app: scenario-container-enforce-probes-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
