apiVersion: v1
kind: Pod
metadata:
  name: pod1
  annotations:
    version-test: 1.0.0-alpha.1
spec:
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  annotations:
    version-test: 1.2.3
spec:
  containers:
  - name: container2
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  annotations:
    version-test: 1.2.3
spec:
  containers:
  - name: container3
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  annotations:
    version-test: 1.0.0-0A.is.legal
spec:
  containers:
  - name: container4
    image: mcr.microsoft.com/aks/policy/example:v1.0.0