apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pass-example-deployment
  namespace: example # detects this field
  labels:
    app: scenario-block-default-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scenario-block-default-namespace
  template:
    metadata:
      labels:
        app: scenario-block-default-namespace
    spec:
      containers:
      - name: container1
        image: mcr.microsoft.com/aks/policy/example:v1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pass-example-service # detects this field
  namespace: example # detects this field
spec:
  ports:
  - port: 8080
