apiVersion: v1
kind: Pod
metadata:
  name: pass-example
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: 100m
        memory: 100M
  - name: container2
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      requests:
        cpu: 100m
        memory: 100M
      limits:
        cpu: 100m
        memory: 100M
  - name: container3
    image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
    resources:
      requests:
        cpu: 10m
        memory: 10M
      limits:
        cpu: 100m
        memory: 100M