apiVersion: v1
kind: Pod
metadata:
  name: violation-pod
spec:
  securityContext:
    runAsNonRoot: false
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:1809
    command:
      - "ping"
      - "-t"
      - "127.0.0.1"
  nodeSelector:
    "kubernetes.io/os": windows
