apiVersion: v1
kind: Pod
metadata:
  name: violation-prefix
  labels:
    app: scenario-disallowed-host-paths-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    hostPath:
      path: /path2 # parent path will be judged as violation
