apiVersion: v1
kind: Pod
metadata:
    name: pass-example
    labels:
        app: scenario-selinux
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    securityContext:
      seLinuxOptions:
        level: s0:c123,c456
        user: system_u
        role: object_r
        type: svirt_sandbox_file_t
