apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-allowed-default-type
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    securityContext:
      procMount: Default # detects this field
