apiVersion: v1
kind: Pod
metadata:
  name: pass-windows
  labels:
    app: scenario-allowed-host-path
spec:
  nodeSelector:
    kubernetes.io/os: windows # will bypass windows containers
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
    volumeMounts:
    - mountPath: C:\var\lib\kubelet
      name: kubelet
      readOnly: true
  volumes:
  - name: kubelet
    hostPath:
      path: C:\var\lib\kubelet