apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-allowed-host-path
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
      readOnly: true # if `allowedHostPaths - readonly` is true. It must set readOnly true when it is mounted
  volumes:
  - name: cache-volume
    hostPath:
      path: /etc # `allowedHostPaths - pathPrefex` detects this field
  - name: not-mounted
    hostPath:
      path: /tmp # if disallowedHostPath is not mounted, it will not report non-complaint
