apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-forbid-kernel-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  securityContext:
    sysctls:
    - name: kernel.msgmax # detects this field
      value: "65536"
