apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-container-allowed-images-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: nginx
    ports:
    - containerPort: 8080