apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-flexvolume-drivers
spec:
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    volumeMounts:
    - mountPath: /test
      name: test-volume
      readOnly: true
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  volumes:
  - name: test-volume
    flexVolume:
      driver: "example/lvm" # detects this field
