apiVersion: apps/v1
kind: Deployment # only check pod
metadata:
  name: pass-example
  labels:
    app: scenario-block-naked-pods
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scenario-block-naked-pods
  template:
    metadata:
      labels:
        app: scenario-block-naked-pods
    spec:
      containers:
      - name: container1
        image: mcr.microsoft.com/aks/policy/example:v1.0.0
