apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-run-as-non-root
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
      runAsNonRoot: false
  containers:
    - name: container1
      image: mcr.microsoft.com/aks/policy/example:v1.0.0
      securityContext:
        runAsNonRoot: true
